[package]
name = "drift"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative = "2.2.0"
proptest = "1.5"
proptest-derive = "0.6.0"
thiserror = "2.0.12"
turmoil = "0.6.6"
tokio = "1.45.1"
rand = "0.9.2"

[features]
turmoil = []
